# Version information.
program_name:       "Scraper"
program_ver:        0.0.1
program_devs:       ["Michael Cvitanovich"]
program_web:        "galacticwingcommander"   
# Window
win_width:          800.0
win_height:         500.0
